export const ADD_BOOKING_RECQUEST = "ADD_BOOKINH_RECQUEST"
export const ADD_BOOKING_SUCCESS = "ADD_BOOKINH_SUCCESS"
export const ADD_BOOKING_FAIL = "ADD_BOOKINH_FAIL"

export const GET_BOOKING_RECQUEST = "GET_BOOKINH_RECQUEST"
export const GET_BOOKING_SUCCESS = "GET_BOOKINH_SUCCESS"
export const GET_BOOKING_FAIL = "GET_BOOKINH_FAIL"

export const DELETE_BOOKING_RECQUEST = " DELETE_BOOKINH_RECQUEST"
export const DELETE_BOOKING_SUCCESS = " DELETE_BOOKINH_SUCCESS"
export const DELETE_BOOKING_FAIL = " DELETE_BOOKINH_FAIL"

export const UPDATE_BOOKING_RECQUEST = " UPDATE_BOOKINH_RECQUEST"
export const UPDATE_BOOKING_SUCCESS = " UPDATE_BOOKINH_SUCCESS"
export const UPDATE_BOOKING_FAIL = " UPDATE_BOOKINH_FAIL"




